version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: alx_db_postgres
    environment:
      - POSTGRES_DB=alx_caching_db
      - POSTGRES_USER=alx_user
      - POSTGRES_PASSWORD=alx_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    container_name: alx_redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data # This line addresses the missing volume
  
volumes:
  postgres_data:
  redis_data: # This line addresses the missing volume
